//! Weekly Torah portions (parshiyot), for Israel and outside it.

use chrono::{Datelike, NaiveDate, Weekday};
use serde::{Deserialize, Serialize};

use crate::calendar::{DateConverter, HebrewDate};
use crate::{CalendarError, Observance};

/// Torah portion
///
/// Includes all 54 standard parshiot plus combined readings (for years
/// where parshiot must be paired to fit the Shabbatot between Simchat
/// Torah and Pesach).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Parsha {
    Bereshit,
    Noach,
    LechLecha,
    Vayera,
    ChayeiSara,
    Toldot,
    Vayetzei,
    Vayishlach,
    Vayeshev,
    Miketz,
    Vayigash,
    Vayechi,
    Shemot,
    Vaera,
    Bo,
    Beshalach,
    Yitro,
    Mishpatim,
    Terumah,
    Tetzaveh,
    KiTisa,
    Vayakhel,
    Pekudei,
    Vayikra,
    Tzav,
    Shemini,
    Tazria,
    Metzora,
    AchreiMot,
    Kedoshim,
    Emor,
    Behar,
    Bechukotai,
    Bamidbar,
    Nasso,
    Behaalotecha,
    Shelach,
    Korach,
    Chukat,
    Balak,
    Pinchas,
    Matot,
    Masei,
    Devarim,
    Vaetchanan,
    Eikev,
    Reeh,
    Shoftim,
    KiTeitzei,
    KiTavo,
    Nitzavim,
    Vayeilech,
    HaAzinu,
    VezotHaberacha,
    // Combined readings
    VayakhelPekudei,
    TazriaMetzora,
    AchreiMotKedoshim,
    BeharBechukotai,
    ChukatBalak,
    MatotMasei,
    NitzavimVayeilech,
}

impl Parsha {
    pub fn name(&self) -> &'static str {
        match self {
            Parsha::Bereshit => "Bereshit",
            Parsha::Noach => "Noach",
            Parsha::LechLecha => "Lech Lecha",
            Parsha::Vayera => "Vayera",
            Parsha::ChayeiSara => "Chayei Sara",
            Parsha::Toldot => "Toldot",
            Parsha::Vayetzei => "Vayetzei",
            Parsha::Vayishlach => "Vayishlach",
            Parsha::Vayeshev => "Vayeshev",
            Parsha::Miketz => "Miketz",
            Parsha::Vayigash => "Vayigash",
            Parsha::Vayechi => "Vayechi",
            Parsha::Shemot => "Shemot",
            Parsha::Vaera => "Vaera",
            Parsha::Bo => "Bo",
            Parsha::Beshalach => "Beshalach",
            Parsha::Yitro => "Yitro",
            Parsha::Mishpatim => "Mishpatim",
            Parsha::Terumah => "Terumah",
            Parsha::Tetzaveh => "Tetzaveh",
            Parsha::KiTisa => "Ki Tisa",
            Parsha::Vayakhel => "Vayakhel",
            Parsha::Pekudei => "Pekudei",
            Parsha::Vayikra => "Vayikra",
            Parsha::Tzav => "Tzav",
            Parsha::Shemini => "Shemini",
            Parsha::Tazria => "Tazria",
            Parsha::Metzora => "Metzora",
            Parsha::AchreiMot => "Achrei Mot",
            Parsha::Kedoshim => "Kedoshim",
            Parsha::Emor => "Emor",
            Parsha::Behar => "Behar",
            Parsha::Bechukotai => "Bechukotai",
            Parsha::Bamidbar => "Bamidbar",
            Parsha::Nasso => "Nasso",
            Parsha::Behaalotecha => "Behaalotecha",
            Parsha::Shelach => "Shelach",
            Parsha::Korach => "Korach",
            Parsha::Chukat => "Chukat",
            Parsha::Balak => "Balak",
            Parsha::Pinchas => "Pinchas",
            Parsha::Matot => "Matot",
            Parsha::Masei => "Masei",
            Parsha::Devarim => "Devarim",
            Parsha::Vaetchanan => "Vaetchanan",
            Parsha::Eikev => "Eikev",
            Parsha::Reeh => "Reeh",
            Parsha::Shoftim => "Shoftim",
            Parsha::KiTeitzei => "Ki Teitzei",
            Parsha::KiTavo => "Ki Tavo",
            Parsha::Nitzavim => "Nitzavim",
            Parsha::Vayeilech => "Vayeilech",
            Parsha::HaAzinu => "HaAzinu",
            Parsha::VezotHaberacha => "Vezot Haberacha",
            Parsha::VayakhelPekudei => "Vayakhel-Pekudei",
            Parsha::TazriaMetzora => "Tazria-Metzora",
            Parsha::AchreiMotKedoshim => "Achrei Mot-Kedoshim",
            Parsha::BeharBechukotai => "Behar-Bechukotai",
            Parsha::ChukatBalak => "Chukat-Balak",
            Parsha::MatotMasei => "Matot-Masei",
            Parsha::NitzavimVayeilech => "Nitzavim-Vayeilech",
        }
    }

    pub fn hebrew_name(&self) -> &'static str {
        match self {
            Parsha::Bereshit => "בראשית",
            Parsha::Noach => "נח",
            Parsha::LechLecha => "לך לך",
            Parsha::Vayera => "וירא",
            Parsha::ChayeiSara => "חיי שרה",
            Parsha::Toldot => "תולדות",
            Parsha::Vayetzei => "ויצא",
            Parsha::Vayishlach => "וישלח",
            Parsha::Vayeshev => "וישב",
            Parsha::Miketz => "מקץ",
            Parsha::Vayigash => "ויגש",
            Parsha::Vayechi => "ויחי",
            Parsha::Shemot => "שמות",
            Parsha::Vaera => "וארא",
            Parsha::Bo => "בא",
            Parsha::Beshalach => "בשלח",
            Parsha::Yitro => "יתרו",
            Parsha::Mishpatim => "משפטים",
            Parsha::Terumah => "תרומה",
            Parsha::Tetzaveh => "תצוה",
            Parsha::KiTisa => "כי תשא",
            Parsha::Vayakhel => "ויקהל",
            Parsha::Pekudei => "פקודי",
            Parsha::Vayikra => "ויקרא",
            Parsha::Tzav => "צו",
            Parsha::Shemini => "שמיני",
            Parsha::Tazria => "תזריע",
            Parsha::Metzora => "מצורע",
            Parsha::AchreiMot => "אחרי מות",
            Parsha::Kedoshim => "קדושים",
            Parsha::Emor => "אמור",
            Parsha::Behar => "בהר",
            Parsha::Bechukotai => "בחקותי",
            Parsha::Bamidbar => "במדבר",
            Parsha::Nasso => "נשא",
            Parsha::Behaalotecha => "בהעלותך",
            Parsha::Shelach => "שלח",
            Parsha::Korach => "קרח",
            Parsha::Chukat => "חקת",
            Parsha::Balak => "בלק",
            Parsha::Pinchas => "פינחס",
            Parsha::Matot => "מטות",
            Parsha::Masei => "מסעי",
            Parsha::Devarim => "דברים",
            Parsha::Vaetchanan => "ואתחנן",
            Parsha::Eikev => "עקב",
            Parsha::Reeh => "ראה",
            Parsha::Shoftim => "שופטים",
            Parsha::KiTeitzei => "כי תצא",
            Parsha::KiTavo => "כי תבוא",
            Parsha::Nitzavim => "נצבים",
            Parsha::Vayeilech => "וילך",
            Parsha::HaAzinu => "האזינו",
            Parsha::VezotHaberacha => "וזאת הברכה",
            Parsha::VayakhelPekudei => "ויקהל-פקודי",
            Parsha::TazriaMetzora => "תזריע-מצורע",
            Parsha::AchreiMotKedoshim => "אחרי מות-קדושים",
            Parsha::BeharBechukotai => "בהר-בחקותי",
            Parsha::ChukatBalak => "חקת-בלק",
            Parsha::MatotMasei => "מטות-מסעי",
            Parsha::NitzavimVayeilech => "נצבים-וילך",
        }
    }

    /// The single portions this reading covers: one, or two for a double.
    pub fn portions(&self) -> Vec<Parsha> {
        match self {
            Parsha::VayakhelPekudei => vec![Parsha::Vayakhel, Parsha::Pekudei],
            Parsha::TazriaMetzora => vec![Parsha::Tazria, Parsha::Metzora],
            Parsha::AchreiMotKedoshim => vec![Parsha::AchreiMot, Parsha::Kedoshim],
            Parsha::BeharBechukotai => vec![Parsha::Behar, Parsha::Bechukotai],
            Parsha::ChukatBalak => vec![Parsha::Chukat, Parsha::Balak],
            Parsha::MatotMasei => vec![Parsha::Matot, Parsha::Masei],
            Parsha::NitzavimVayeilech => vec![Parsha::Nitzavim, Parsha::Vayeilech],
            single => vec![*single],
        }
    }

    /// Position in the Torah, Bereshit = 0 to Vezot HaBerachah = 53. A double
    /// portion has the index of its first half.
    pub fn index(&self) -> usize {
        let first = self.portions()[0];
        if first == Parsha::VezotHaberacha {
            return 53;
        }
        SINGLES
            .iter()
            .position(|p| *p == first)
            .expect("every single portion is listed")
    }
}

/// Weekly Torah portions.
///
/// Each Hebrew year's readings are fixed by three facts about it: whether it
/// is a leap year, the weekday of Rosh Hashanah, and whether Cheshvan and
/// Kislev are short, regular or long. That gives fourteen kinds of year, and
/// for each one the sequence of Shabbat readings, from the first Shabbat on or
/// after Rosh Hashanah to the last one before the next, is a fixed list.
/// Outside Israel a festival's second day can fall on Shabbat and push the
/// portions a week behind Israel's until a double portion catches them up, so
/// each kind of year has two lists. The lists below were read off Hebcal's
/// schedule for 1950–2080 (every year of a kind gave the same list), and the
/// review harness checks them against it for every Shabbat in that range.
pub struct ParshaCalculator;

/// One Shabbat in a schedule.
#[derive(Clone, Copy)]
enum Entry {
    /// A single portion, by its index from Bereshit (0) to Ha'azinu (52).
    S(u8),
    /// Two portions read together, starting at this index.
    D(u8),
    /// A festival reading replaces the weekly portion.
    C,
}
use Entry::{C, D, S};

/// Short, regular or long year: Cheshvan and Kislev both 29 days, 29 and 30,
/// or both 30.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum YearKind {
    Deficient,
    Regular,
    Complete,
}

const SINGLES: [Parsha; 53] = [
    Parsha::Bereshit,
    Parsha::Noach,
    Parsha::LechLecha,
    Parsha::Vayera,
    Parsha::ChayeiSara,
    Parsha::Toldot,
    Parsha::Vayetzei,
    Parsha::Vayishlach,
    Parsha::Vayeshev,
    Parsha::Miketz,
    Parsha::Vayigash,
    Parsha::Vayechi,
    Parsha::Shemot,
    Parsha::Vaera,
    Parsha::Bo,
    Parsha::Beshalach,
    Parsha::Yitro,
    Parsha::Mishpatim,
    Parsha::Terumah,
    Parsha::Tetzaveh,
    Parsha::KiTisa,
    Parsha::Vayakhel,
    Parsha::Pekudei,
    Parsha::Vayikra,
    Parsha::Tzav,
    Parsha::Shemini,
    Parsha::Tazria,
    Parsha::Metzora,
    Parsha::AchreiMot,
    Parsha::Kedoshim,
    Parsha::Emor,
    Parsha::Behar,
    Parsha::Bechukotai,
    Parsha::Bamidbar,
    Parsha::Nasso,
    Parsha::Behaalotecha,
    Parsha::Shelach,
    Parsha::Korach,
    Parsha::Chukat,
    Parsha::Balak,
    Parsha::Pinchas,
    Parsha::Matot,
    Parsha::Masei,
    Parsha::Devarim,
    Parsha::Vaetchanan,
    Parsha::Eikev,
    Parsha::Reeh,
    Parsha::Shoftim,
    Parsha::KiTeitzei,
    Parsha::KiTavo,
    Parsha::Nitzavim,
    Parsha::Vayeilech,
    Parsha::HaAzinu,
];

impl ParshaCalculator {
    /// The portion read outside Israel on the Shabbat on or after `date`, or
    /// `None` when a festival reading replaces it that week.
    pub fn get_parsha(date: &HebrewDate) -> Result<Option<Parsha>, CalendarError> {
        Self::get_parsha_for(date, Observance::Diaspora)
    }

    /// The portion read on the Shabbat on or after `date`, or `None` when a
    /// festival reading replaces it that week.
    pub fn get_parsha_for(
        date: &HebrewDate,
        observance: Observance,
    ) -> Result<Option<Parsha>, CalendarError> {
        let shabbat = Self::next_shabbat(DateConverter::hebrew_to_gregorian(*date)?);
        let shabbat_rd = DateConverter::gregorian_to_rd(shabbat);
        let year = DateConverter::gregorian_to_hebrew(shabbat)?.year;
        let (mut first, mut schedule) = Self::schedule(year, observance)?;
        if shabbat_rd < first {
            (first, schedule) = Self::schedule(year - 1, observance)?;
        }
        let week = ((shabbat_rd - first) / 7) as usize;
        schedule.get(week).map(|e| Self::parsha(*e)).ok_or_else(|| {
            CalendarError::CalculationError(format!("no reading for week {week} of year {year}"))
        })
    }

    /// Every Shabbat of Hebrew year `year` with its reading.
    pub fn year_readings(
        year: i32,
        observance: Observance,
    ) -> Result<Vec<(NaiveDate, Option<Parsha>)>, CalendarError> {
        let (first, schedule) = Self::schedule(year, observance)?;
        schedule
            .iter()
            .enumerate()
            .map(|(i, e)| {
                let date = DateConverter::rd_to_gregorian(first + 7 * i as i32)?;
                Ok((date, Self::parsha(*e)))
            })
            .collect()
    }

    /// The Shabbat on or after `date`.
    pub fn next_shabbat(date: NaiveDate) -> NaiveDate {
        let ahead = (6 - date.weekday().num_days_from_sunday() as i64).rem_euclid(7);
        date + chrono::Duration::days(ahead)
    }

    fn parsha(entry: Entry) -> Option<Parsha> {
        match entry {
            S(i) => Some(SINGLES[i as usize]),
            D(i) => Some(match i {
                21 => Parsha::VayakhelPekudei,
                26 => Parsha::TazriaMetzora,
                28 => Parsha::AchreiMotKedoshim,
                31 => Parsha::BeharBechukotai,
                38 => Parsha::ChukatBalak,
                41 => Parsha::MatotMasei,
                50 => Parsha::NitzavimVayeilech,
                _ => unreachable!("no double portion starts at {i}"),
            }),
            C => None,
        }
    }

    /// The first Shabbat on or after Rosh Hashanah of `year` (R.D.) and the
    /// year's readings from there.
    fn schedule(
        year: i32,
        observance: Observance,
    ) -> Result<(i32, &'static [Entry]), CalendarError> {
        let rosh_hashanah = DateConverter::rosh_hashanah(year);
        let weekday = DateConverter::rd_to_gregorian(rosh_hashanah)?.weekday();
        let first = rosh_hashanah + (6 - weekday.num_days_from_sunday() as i32).rem_euclid(7);
        let leap = DateConverter::is_hebrew_leap_year(year);
        let kind = match DateConverter::days_in_hebrew_year(year) {
            353 | 383 => YearKind::Deficient,
            354 | 384 => YearKind::Regular,
            _ => YearKind::Complete,
        };
        let schedule = match observance {
            Observance::Diaspora => Self::diaspora_schedule(leap, weekday, kind),
            Observance::Israel => Self::israel_schedule(leap, weekday, kind),
        };
        schedule.map(|s| (first, s)).ok_or_else(|| {
            CalendarError::CalculationError(format!(
                "no reading schedule for year {year} ({kind:?}, Rosh Hashanah on {weekday})"
            ))
        })
    }

    /// Readings outside Israel.
    fn diaspora_schedule(
        leap: bool,
        rosh_hashanah: Weekday,
        kind: YearKind,
    ) -> Option<&'static [Entry]> {
        use Weekday::*;
        use YearKind::*;
        Some(match (leap, rosh_hashanah, kind) {
            (false, Mon, Deficient) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (false, Mon, Complete) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                C,
                S(34),
                S(35),
                S(36),
                S(37),
                D(38),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (false, Tue, Regular) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                C,
                S(34),
                S(35),
                S(36),
                S(37),
                D(38),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (false, Thu, Regular) => &[
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (false, Thu, Complete) => &[
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (false, Sat, Deficient) => &[
                C,
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (false, Sat, Complete) => &[
                C,
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (true, Mon, Deficient) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                C,
                S(28),
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                C,
                S(34),
                S(35),
                S(36),
                S(37),
                D(38),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (true, Mon, Complete) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                C,
                C,
                S(28),
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (true, Tue, Regular) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                C,
                C,
                S(28),
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (true, Thu, Deficient) => &[
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                S(28),
                C,
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                S(41),
                S(42),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (true, Thu, Complete) => &[
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                S(28),
                C,
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                S(41),
                S(42),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (true, Sat, Deficient) => &[
                C,
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                C,
                S(28),
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (true, Sat, Complete) => &[
                C,
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                C,
                S(28),
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                C,
                S(34),
                S(35),
                S(36),
                S(37),
                D(38),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            _ => return None,
        })
    }

    /// Readings in Israel.
    fn israel_schedule(
        leap: bool,
        rosh_hashanah: Weekday,
        kind: YearKind,
    ) -> Option<&'static [Entry]> {
        use Weekday::*;
        use YearKind::*;
        Some(match (leap, rosh_hashanah, kind) {
            (false, Mon, Deficient) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (false, Mon, Complete) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (false, Tue, Regular) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (false, Thu, Regular) => &[
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (false, Thu, Complete) => &[
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (false, Sat, Deficient) => &[
                C,
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (false, Sat, Complete) => &[
                C,
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                D(21),
                S(23),
                S(24),
                C,
                S(25),
                D(26),
                D(28),
                S(30),
                D(31),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (true, Mon, Deficient) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                C,
                S(28),
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (true, Mon, Complete) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                C,
                S(28),
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                S(41),
                S(42),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (true, Tue, Regular) => &[
                S(51),
                S(52),
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                C,
                S(28),
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                S(41),
                S(42),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (true, Thu, Deficient) => &[
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                S(28),
                C,
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                S(41),
                S(42),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                S(50),
            ],
            (true, Thu, Complete) => &[
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                S(28),
                C,
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                S(41),
                S(42),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (true, Sat, Deficient) => &[
                C,
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                C,
                S(28),
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            (true, Sat, Complete) => &[
                C,
                S(52),
                C,
                C,
                S(0),
                S(1),
                S(2),
                S(3),
                S(4),
                S(5),
                S(6),
                S(7),
                S(8),
                S(9),
                S(10),
                S(11),
                S(12),
                S(13),
                S(14),
                S(15),
                S(16),
                S(17),
                S(18),
                S(19),
                S(20),
                S(21),
                S(22),
                S(23),
                S(24),
                S(25),
                S(26),
                S(27),
                C,
                S(28),
                S(29),
                S(30),
                S(31),
                S(32),
                S(33),
                S(34),
                S(35),
                S(36),
                S(37),
                S(38),
                S(39),
                S(40),
                D(41),
                S(43),
                S(44),
                S(45),
                S(46),
                S(47),
                S(48),
                S(49),
                D(50),
            ],
            _ => return None,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::calendar::HebrewMonth;

    fn on(y: i32, m: u32, d: u32, observance: Observance) -> Option<Parsha> {
        let g = NaiveDate::from_ymd_opt(y, m, d).unwrap();
        let h = DateConverter::gregorian_to_hebrew(g).unwrap();
        ParshaCalculator::get_parsha_for(&h, observance).unwrap()
    }

    #[test]
    fn every_year_of_three_centuries_reads_the_whole_torah() {
        for year in 5600..5900 {
            for observance in [Observance::Diaspora, Observance::Israel] {
                let readings = ParshaCalculator::year_readings(year, observance).unwrap();
                let mut read = Vec::new();
                for (_, p) in &readings {
                    if let Some(p) = p {
                        read.extend(p.portions())
                    }
                }
                // Each Hebrew year reads Ha'azinu (and sometimes Vayeilech)
                // of the previous cycle first, then Bereshit through Nitzavim.
                let start = read.iter().position(|p| *p == Parsha::Bereshit).unwrap();
                let cycle = &read[start..];
                assert_eq!(
                    cycle.first(),
                    Some(&Parsha::Bereshit),
                    "{year} {observance:?}"
                );
                for pair in cycle.windows(2) {
                    assert_eq!(
                        pair[1].index(),
                        pair[0].index() + 1,
                        "{year} {observance:?}: {:?} then {:?}",
                        pair[0],
                        pair[1]
                    );
                }
            }
        }
    }

    #[test]
    fn diaspora_5784_against_hebcal() {
        use Parsha::*;
        let cases = [
            (2023, 10, 14, Some(Bereshit)),
            (2023, 10, 21, Some(Noach)),
            (2024, 3, 9, Some(Vayakhel)),
            (2024, 3, 16, Some(Pekudei)),
            (2024, 4, 20, Some(Metzora)),
            (2024, 4, 27, None), // Pesach, Chol HaMoed
            (2024, 5, 4, Some(AchreiMot)),
            (2024, 8, 3, Some(MatotMasei)),
            (2024, 9, 28, Some(NitzavimVayeilech)),
            (2024, 10, 5, Some(HaAzinu)),
        ];
        for (y, m, d, expected) in cases {
            assert_eq!(on(y, m, d, Observance::Diaspora), expected, "{y}-{m}-{d}");
        }
    }

    #[test]
    fn israel_runs_a_week_ahead_after_a_festival_shabbat() {
        // 1955: the second day of Shavuot fell on Shabbat 28 May, outside Israel only.
        assert_eq!(on(1955, 5, 28, Observance::Diaspora), None);
        assert_eq!(on(1955, 5, 28, Observance::Israel), Some(Parsha::Nasso));
        assert_eq!(on(1955, 6, 4, Observance::Diaspora), Some(Parsha::Nasso));
        // The diaspora catches up by reading Chukat and Balak together.
        assert_eq!(
            on(1955, 7, 2, Observance::Diaspora),
            Some(Parsha::ChukatBalak)
        );
        assert_eq!(on(1955, 7, 2, Observance::Israel), Some(Parsha::Balak));
    }

    #[test]
    fn a_weekday_gives_the_coming_shabbat() {
        // Sunday 15 October 2023 → Shabbat 21 October, Noach.
        let sunday = HebrewDate::new(5784, HebrewMonth::Tishrei, 30);
        assert_eq!(
            ParshaCalculator::get_parsha(&sunday).unwrap(),
            Some(Parsha::Noach)
        );
    }

    #[test]
    fn names() {
        assert_eq!(Parsha::Bereshit.name(), "Bereshit");
        assert_eq!(Parsha::Bereshit.hebrew_name(), "בראשית");
        assert_eq!(Parsha::VayakhelPekudei.name(), "Vayakhel-Pekudei");
        assert_eq!(
            Parsha::VayakhelPekudei.portions(),
            vec![Parsha::Vayakhel, Parsha::Pekudei]
        );
    }
}
